
import { teams } from '../data/gameData.js';
import { MANAGER_JOB_MARKET_VERSION, MANAGER_MARKET_TIERS, MANAGER_CLUB_MARKET, MANAGER_NATIONAL_MARKET, MANAGER_MARKET_EVENTS } from '../data/managerJobMarketData.js';
function clamp(n,min=0,max=100){return Math.max(min,Math.min(max,Number(n||0)));}
function tierFor(k){return MANAGER_MARKET_TIERS.find(t=>t.key===k)||MANAGER_MARKET_TIERS[0];}
function seed(t=''){let s=0;for(const c of t)s=(s*31+c.charCodeAt(0))%9973;return s;}
function power(state={}){const rep=clamp(state.manager?.reputation||50), lvl=Number(state.career?.managerProgression?.level||1), board=clamp(state.boardTrust||60), fan=clamp(state.fanMood||60), seasons=Number(state.career?.completedSeasons||0);return clamp(rep*.62+board*.12+fan*.08+Math.min(12,lvl*1.7)+Math.min(8,seasons*2));}
function fit(item,state={},i=0){const tr=tierFor(item.tier);return clamp(Math.round(tr.fitBase+(power(state)-tr.minRep)*.42+((seed(`${item.id}-${state.season}-${i}`)%17)-8)),20,96);}
function status(f){return f>=82?'Proposta formal':f>=66?'Sondagem avançada':f>=50?'Monitoramento':'Sondagem distante';}
function wage(item,f){const [a,b]=tierFor(item.tier).wage;return Number((a+(b-a)*clamp(f)/100).toFixed(2));}
function currentClubId(s){return s.clubId||s.ui?.selectedClub||'santos';}
export function normalizeManagerJobMarket(state={}){const b=state.career?.jobMarket||{};return {version:MANAGER_JOB_MARKET_VERSION,lastGeneratedAt:b.lastGeneratedAt||null,rumors:Array.isArray(b.rumors)?b.rumors.slice(-10):[],decisionLog:Array.isArray(b.decisionLog)?b.decisionLog.slice(-30):[],acceptedOffers:Array.isArray(b.acceptedOffers)?b.acceptedOffers.slice(-12):[],rejectedOffers:Array.isArray(b.rejectedOffers)?b.rejectedOffers.slice(-20):[],negotiationMood:b.negotiationMood||'Estável'};}
export function generateRealManagerOffers(state={}){const current=currentClubId(state);const clubs=MANAGER_CLUB_MARKET.filter(c=>c.id!==current).map((c,i)=>{const f=fit(c,state,i), w=wage(c,f), tr=tierFor(c.tier);return {id:`job-${c.id}-${state.season||2026}-${f}`,type:'club',targetId:c.id,name:c.name,country:c.country,league:c.league,role:c.role,status:status(f),requiredRep:tr.minRep,fit:f,objective:c.objective,pressure:tr.pressure,calendar:'Liga, copas nacionais e competições internacionais',wage:w,releaseClause:Number((w*8).toFixed(2)),months:c.tier==='elite'?24:f>75?30:18,project:c.project,negotiationRisk:f<62?'alto':f<78?'médio':'baixo',rumor:`${c.name} avalia seu perfil para um projeto de ${c.style}.`,canAccept:f>=Math.max(45,tr.minRep-8)}}).sort((a,b)=>b.fit-a.fit).slice(0,6);const nations=MANAGER_NATIONAL_MARKET.map((n,i)=>{const f=fit(n,state,i+30), w=wage(n,f), tr=tierFor(n.tier);return {id:`job-${n.id}-${state.season||2026}-${f}`,type:'national',targetId:n.id,name:n.name,country:n.country,role:n.role,status:status(f),requiredRep:tr.minRep,fit:f,objective:n.objective,pressure:n.pressure,calendar:n.calendar,wage:w,releaseClause:0,months:24,project:'Ciclo internacional paralelo ao clube',negotiationRisk:f<70?'médio':'baixo',rumor:`${n.name} observa sua evolução para o próximo ciclo internacional.`,canAccept:f>=Math.max(55,tr.minRep-5)}}).filter(o=>power(state)>=Math.max(45,o.requiredRep-12)||o.fit>=60).sort((a,b)=>b.fit-a.fit).slice(0,3);return [...clubs,...nations].slice(0,8);}
export function buildManagerJobMarketSnapshot(state={}){const jm=normalizeManagerJobMarket(state);const offers=Array.isArray(state.career?.jobOffers)&&state.career.jobOffers.length?state.career.jobOffers:generateRealManagerOffers(state);const best=[...offers].sort((a,b)=>Number(b.fit||0)-Number(a.fit||0))[0];const team=teams.find(t=>t.id===currentClubId(state));return {version:MANAGER_JOB_MARKET_VERSION,power:Math.round(power(state)),currentClub:team?.name||currentClubId(state),currentWage:Number(state.career?.activeContract?.wageMonthly||.8),activeOffers:offers.length,formalOffers:offers.filter(o=>String(o.status||'').includes('Proposta')).length,bestOffer:best,rumors:jm.rumors.length?jm.rumors:MANAGER_MARKET_EVENTS.slice(0,4),decisionLog:jm.decisionLog,acceptedOffers:jm.acceptedOffers,rejectedOffers:jm.rejectedOffers,negotiationMood:jm.negotiationMood};}
export function createJobMarketPatch(state={}){const offers=generateRealManagerOffers(state);const rumors=offers.slice(0,4).map(o=>o.rumor);return {jobOffers:offers,jobMarket:{...normalizeManagerJobMarket(state),version:MANAGER_JOB_MARKET_VERSION,lastGeneratedAt:new Date().toISOString(),rumors,negotiationMood:offers.some(o=>o.status==='Proposta formal')?'Aquecido':'Monitorando mercado'}};}
export function registerJobDecisionPatch(state={},offer={},decision='reject'){const jm=normalizeManagerJobMarket(state), stamp=new Date().toISOString().slice(0,10), key=decision==='accept'?'acceptedOffers':'rejectedOffers';const text=`${stamp}: ${decision==='accept'?'Aceitou':'Recusou'} ${offer.type==='national'?'seleção':'clube'} ${offer.name} (${offer.status||'sondagem'}).`;return {...jm,decisionLog:[text,...jm.decisionLog].slice(0,30),[key]:[{id:offer.id,name:offer.name,type:offer.type,date:stamp,wage:offer.wage,fit:offer.fit},...jm[key]].slice(0,decision==='accept'?12:20),negotiationMood:decision==='accept'?'Novo contrato assinado':'Mercado segue aberto'};}
