import { safeImg, clubLogo, country } from '../systems/assets.js';
import { visualBackground } from '../systems/visualAssetManager.js';
import { screens, teams } from '../data/gameData.js';
import { money } from '../utils/dom.js';
import { NAVIGATION_ROUTES_V560 } from '../systems/navigationExperienceEngine.js';
export function screenWrap(key, content, nav=true){ const cls = `screen screen-${key} v540-mobile-shell ${nav?'':'no-bottom-nav'}`; const matchHint = key === 'match' ? `<div class="orientation-hint-v540"><div><strong>Modo partida</strong><span>Vire o celular na horizontal para campo, placar e comandos ficarem no padrão console.</span></div><button class="secondary-btn mini" data-action="ui-fullscreen">Tela cheia</button></div>` : ''; return `<main class="${cls}" style="background-image:url('${visualBackground(key)}')">${matchHint}<button class="fullscreen-fab-v540" data-action="ui-fullscreen" aria-label="Ativar tela cheia">⛶</button>${content}${nav?bottomNav():''}<div class="build-badge" id="buildBadge"></div></main>`; }
export function brand(size='') { return `<div class="brand ${size}"><span class="gold">VALE</span><br>FUTEBOL<br><span class="gold">MANAGER</span><div class="tag">GOLD EDITION</div></div>`; }
export function topbar(title, subtitle='', back='lobby', options={}){ const showResources = options.resources !== false; const right = showResources ? `<div class="row topbar-resources"><div class="resource">💵 € 92.5M</div><div class="resource">🪙 250</div><button class="icon-btn" data-route="messages">✉</button><button class="icon-btn" data-route="settings">?</button></div>` : `<div class="row topbar-clean"><span class="tag">Criação de carreira</span></div>`; return `<div class="topbar"><button class="icon-btn" data-route="${back}" aria-label="Voltar">‹</button><div><div class="title">${title}</div>${subtitle?`<div class="subtitle">${subtitle}</div>`:''}</div>${right}</div>`; }
export function clubHeader(state){ const team = teams.find(t=>t.id===state.clubId) || teams[0]; return `<div class="header-club">${safeImg(clubLogo(team.id),'club',team.name,'club-logo')}<div><h2>${team.name}</h2><div class="row small">${safeImg(country(team.country),'country',team.countryName,'','')} ${team.countryName} · ${state.manager.name} · <span class="tag">${state.manager.reputation}</span></div></div></div>`; }
export function bottomNav(){ return `<nav class="bottom-nav nav-v560" aria-label="Navegação principal">${NAVIGATION_ROUTES_V560.map(item=>`<button class="nav-item nav-v560-item ${item.primary?'nav-v560-play':''}" data-route="${item.route}" data-nav-route="${item.route}" aria-label="${item.label}"><span class="nav-icon">${item.icon}</span><span class="nav-label">${item.label}</span><span class="nav-hint">${item.hint || ''}</span></button>`).join('')}</nav>`; }
export function moneyCard(label,value){ return `<div class="card"><div class="small">${label}</div><strong>${money(value)}</strong></div>`; }
