import { screenWrap, topbar, clubHeader } from './common.js';
import { players, tableRows } from '../data/gameData.js';
import { safeImg } from '../systems/assets.js';
export function moduleScreen(route,title,subtitle,state){
  const extra = content(route);
  return screenWrap(route, `${topbar(title,subtitle,'lobby')}${clubHeader(state)}${extra}`, true);
}
function content(route){
  if(route==='formation') return `<section class="grid grid-2"><div class="pitch">${players.map((p,i)=>`<div class="player-dot" style="left:${20+(i%3)*28}%;top:${12+Math.floor(i/3)*20}%">${p[1]}</div>`).join('')}</div><div class="panel stack"><h3>4-3-3 Ofensivo</h3><div class="stat-line"><span>Estilo</span><strong>Posse de bola</strong></div><div class="stat-line"><span>Mentalidade</span><strong>Ofensiva</strong></div><button class="main-btn" data-route="instructions">Instruções</button></div></section>`;
  if(route==='instructions') return `<section class="grid grid-2"><div class="panel stack"><h3>Esquema tático</h3><div class="pitch"></div><button class="secondary-btn">Mentalidade: Ofensiva</button></div><div class="panel stack"><h3>Estilo de jogo</h3>${['Ritmo alto','Largura aberta','Passes curtos','Pressão alta','Linha defensiva alta'].map(x=>`<div class="stat-line"><span>${x}</span><strong>Ativo</strong></div>`).join('')}<button class="main-btn">Salvar instruções</button></div></section>`;
  if(route==='standings') return `<section class="panel"><h3>Selecione a competição</h3><div class="grid grid-3"><button class="card">Brasileirão</button><button class="card">Copa do Brasil</button><button class="card">Sul-Americana</button></div><table class="table"><thead><tr><th>Pos</th><th>Time</th><th>J</th><th>PTS</th></tr></thead><tbody>${tableRows.map((t,i)=>`<tr><td>${i+1}</td><td>${t}</td><td>10</td><td>${23-i}</td></tr>`).join('')}</tbody></table></section>`;
  if(route==='transfers') return `<section class="grid grid-2"><div class="panel"><h3>Jogadores disponíveis</h3>${['Matias Rojas','Gabriel Veron','Lucas Esquivel','Juan Sforza','Rony Lopes'].map((p,i)=>`<div class="stat-line"><span>${p}</span><strong>€ ${(6-i*.7).toFixed(1)}M</strong></div>`).join('')}</div><div class="panel"><h3>Negociações</h3><p class="alert">Mercado preparado para compra, venda, empréstimo e renovação nas próximas builds.</p><button class="main-btn">Buscar jogadores</button></div></section>`;
  if(route==='training') return `<section class="grid grid-2"><div class="panel"><h3>Tema do treino</h3><h2>Posse de bola</h2><p class="small">Melhora circulação, passe e movimentação.</p><div class="meter"><span style="width:65%"></span></div></div><div class="panel"><h3>Jogadores em foco</h3>${players.slice(0,5).map(p=>`<div class="stat-line"><span>${p[0]}</span><strong>${p[2]}</strong></div>`).join('')}</div></section>`;
  if(route==='staff') return `<section class="grid grid-2"><div class="panel"><h3>Equipe atual</h3>${['Treinador','Auxiliar','Médico','Fisioterapeuta','Olheiro','Diretor Comercial'].map(x=>`<div class="stat-line"><span>${x}</span><strong>Contratado</strong></div>`).join('')}</div><div class="panel"><h3>Contratações disponíveis</h3>${['Vagner Mancini','Jair Ventura','Pablo Fernandez','Lucas Itaberaba'].map(x=>`<div class="stat-line"><span>${x}</span><button class="secondary-btn">Contratar</button></div>`).join('')}</div></section>`;
  if(route==='sponsorship') return `<section class="grid grid-2"><div class="panel"><h3>Patrocinadores ativos</h3>${['Blaze','Binance','Umbro','Philco'].map(x=>`<div class="stat-line"><span>${x}</span><strong>Ativo</strong></div>`).join('')}</div><div class="panel"><h3>Propostas</h3>${['Pixbet','1XBet','Brahma'].map(x=>`<div class="card"><strong>${x}</strong><p class="small">Proposta disponível</p></div>`).join('')}</div></section>`;
  if(route==='championship'||route==='calendar') return `<section class="grid"><div class="panel"><h3>Agenda anual</h3><div class="grid grid-2 desktop-4">${['Brasileirão Série A','Copa do Brasil','Sul-Americana','Paulistão'].map(x=>`<div class="card"><h3>${x}</h3><p class="small">Fase atual preparada</p></div>`).join('')}</div></div><div class="panel"><h3>Próximos jogos</h3>${['Santos x Palmeiras','Santos x Flamengo','Grêmio x Santos','Unión x Santos'].map(x=>`<div class="stat-line"><span>${x}</span><strong>20:00</strong></div>`).join('')}</div></section>`;
  if(route==='club') return `<section class="grid grid-2"><div class="panel"><h3>Resumo do clube</h3><div class="stat-line"><span>Reputação</span><strong>★★★★★</strong></div><div class="stat-line"><span>Torcida</span><strong>Fanática</strong></div><div class="stat-line"><span>Estádio</span><strong>Vila Belmiro</strong></div></div><div class="panel"><h3>Finanças</h3><div class="stat-line"><span>Saldo</span><strong>€ 92.5M</strong></div><div class="stat-line"><span>Receita</span><strong>€ 128.4M</strong></div><div class="stat-line"><span>Salários</span><strong>€ 5.32M</strong></div></div></section>`;
  if(route==='settings') return `<section class="grid grid-2"><div class="panel"><h3>Geral</h3>${['Salvar automaticamente','Dicas','Negociações realistas','Lesões','Progresso offline'].map(x=>`<div class="stat-line"><span>${x}</span><strong>Ativo</strong></div>`).join('')}<button class="secondary-btn" data-action="reset-save">Resetar save</button></div><div class="panel"><h3>Qualidade</h3><p class="alert">Build anti-quebra: fallbacks de assets, rotas seguras, salvamento local protegido e auditoria de arquivos.</p></div></section>`;
  return `<section class="module-placeholder panel"><h1>Módulo preparado</h1><p class="subtitle">Esta tela já possui rota segura e será expandida nas próximas builds.</p><button class="main-btn" data-route="lobby">Voltar ao lobby</button></section>`;
}
